on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'test'
        required: true
        type: choice
        options:
          - prod

jobs:
  deploy:
    name: Deploy
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployed!'