name: Create Pull Request with next release version
run-name: "Create Pull Request with next release version"

# This workflow is triggered manually with two inputs: environment and skipPreview
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump option'
        required: true
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  get_latest_release_version:
    name: Get Latest Release Version
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      next_tag: ${{ steps.increment_tag.outputs.next_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get Latest Release Version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          

      - id: increment_tag
        name: Increment tag based on input
        # example $latest_tag = v0.6
        run: |
            latest_tag=${latest_tag#v}
            IFS='.' read -r -a version <<< "$latest_tag"
            echo "Version: ${version[@]}"
            major=${version[0]:-0}
            minor=${version[1]:-0}
            patch=${version[2]:-0}
            case "${{ github.event.inputs.version }}" in
            Major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
            Minor)
            minor=$((minor + 1))
            patch=0
            ;;
            Patch)
            patch=$((patch + 1))
            ;;
            esac
            next_tag="v$major.$minor.$patch"
            echo "Next tag: $next_tag"
            echo "next_tag=$next_tag" >> $GITHUB_ENV
            echo "{next_tag: $next_tag}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [get_latest_release_version]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEXT_TAG: ${{ needs.get_latest_release_version.outputs.next_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Pull Request
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config set advice.refSyntax false
          git checkout -b release/${{ env.NEXT_TAG }}
          git commit --allow-empty -m "Release version ${{ env.NEXT_TAG}}"
          git push origin release/${{ env.NEXT_TAG }}
          gh pr create --base main --head release/${{ env.NEXT_TAG }} --title "Release version ${{ env.NEXT_TAG }}" --body "Release version ${{ env.NEXT_TAG }}"
