name: Create Pull Request with next release version
run-name: "Create Pull Request with next release version"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump option'
        required: true
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  get_latest_release_version:
    name: Get Latest Release Version
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get Latest Release Version
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "$latest_tag"
      - name: Increment tag based on input
        run: |
            latest_tag=${latest_tag#v}
            IFS='.' read -r -a version <<< "$latest_tag"
            echo "Version: $version[0].$version[1].$version[2]"
            major=${version[0]:-0}
            minor=${version[1]:-0}
            patch=${version[2]:-0}
            case "${{ github.event.inputs.version }}" in
            Major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
            Minor)
            minor=$((minor + 1))
            patch=0
            ;;
            Patch)
            patch=$((patch + 1))
            ;;
            esac
            next_tag="v$major.$minor.$patch"
            echo "Next tag: $next_tag"
